create table if not exists public.aion2_dps_rank (
  id bigint generated by default as identity primary key,

  record_id text not null,
  battle_ended_at timestamptz null,

  target_mob_code bigint not null,
  target_name text null,
  is_boss boolean not null default false,
  target_max_hp bigint null,

  main_actor_name text not null,
  main_actor_server_id text not null default '',
  main_actor_class text not null default '',

  main_actor_damage bigint not null default 0,
  main_actor_battle_duration double precision not null default 0,
  main_actor_dps double precision not null default 0,

  party_total_damage bigint not null default 0,
  team_battle_duration double precision not null default 0,
  team_dps double precision not null default 0,

  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),

  constraint aion2_dps_rank_unique_actor_per_boss
    unique (target_mob_code, main_actor_name, main_actor_server_id, main_actor_class)
);

create index if not exists idx_aion2_dps_rank_target_mob_code
  on public.aion2_dps_rank (target_mob_code);

create index if not exists idx_aion2_dps_rank_target_mob_code_actor_class
  on public.aion2_dps_rank (target_mob_code, main_actor_class);

create index if not exists idx_aion2_dps_rank_target_mob_code_main_actor_dps
  on public.aion2_dps_rank (target_mob_code, main_actor_dps desc);

create index if not exists idx_aion2_dps_rank_actor_lookup
  on public.aion2_dps_rank (main_actor_name, main_actor_server_id, battle_ended_at desc);

create index if not exists idx_aion2_dps_rank_battle_ended_at
  on public.aion2_dps_rank (battle_ended_at desc);

create or replace function public.set_aion2_dps_rank_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trg_aion2_dps_rank_updated_at on public.aion2_dps_rank;

create trigger trg_aion2_dps_rank_updated_at
before update on public.aion2_dps_rank
for each row
execute function public.set_aion2_dps_rank_updated_at();
