create table if not exists public.aion2_dps_ingest_queue (
  id bigint generated by default as identity primary key,
  record_id text not null unique,
  payload jsonb not null,
  keep_limit integer not null default 10,
  status text not null default 'pending'
    check (status in ('pending', 'processing', 'done', 'failed')),
  attempts integer not null default 0,
  error text null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  processed_at timestamptz null
);

-- A single battle record can produce multiple rank rows, one per teammate.
-- record_id is therefore a lookup key, not a unique key, in aion2_dps_rank.
drop index if exists public.idx_aion2_dps_rank_record_id;

create index idx_aion2_dps_rank_record_id
  on public.aion2_dps_rank (record_id);

drop index if exists public.idx_aion2_dps_ingest_queue_pending;

create index idx_aion2_dps_ingest_queue_pending
  on public.aion2_dps_ingest_queue (status, created_at, id)
  where status in ('pending', 'failed');

create or replace function public.get_aion2_dps_max_party_total_damage(
  p_mob_code bigint
)
returns bigint
language sql
stable
as $helper$
  select max(party_total_damage)
  from public.aion2_dps
  where target_mob_code = p_mob_code;
$helper$;

create or replace function public.set_aion2_dps_ingest_queue_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trg_aion2_dps_ingest_queue_updated_at on public.aion2_dps_ingest_queue;

create trigger trg_aion2_dps_ingest_queue_updated_at
before update on public.aion2_dps_ingest_queue
for each row
execute function public.set_aion2_dps_ingest_queue_updated_at();

create or replace function public.sanitize_aion2_dps_payload(
  p_payload jsonb
)
returns jsonb
language plpgsql
immutable
as $$
declare
  v_data jsonb;
  v_target_id text;
  v_combat_infos jsonb;
  v_top_keys text[];
begin
  if not (p_payload ? 'data') then
    return p_payload;
  end if;

  v_data := p_payload->'data';

  -- 1. Remove thisTargetAllPlayerSkillRecords entirely (not needed for rank/display)
  v_data := v_data - 'thisTargetAllPlayerSkillRecords';

  -- 2. Find top 12 player keys by total_damage in thisTargetAllPlayerStats
  select array_agg(key order by (value->>'total_damage')::numeric desc)
  into v_top_keys
  from jsonb_each(coalesce(v_data->'thisTargetAllPlayerStats', '{}'::jsonb))
  limit 12;

  -- 3. Keep only top 12 players in thisTargetAllPlayerStats
  if v_top_keys is not null then
    v_data := v_data || jsonb_build_object(
      'thisTargetAllPlayerStats',
      coalesce((
        select jsonb_object_agg(key, value)
        from jsonb_each(coalesce(v_data->'thisTargetAllPlayerStats', '{}'::jsonb))
        where key = any(v_top_keys)
      ), '{}'::jsonb)
    );

    -- 4. Keep only top 12 players in thisTargetAllPlayerSkillStats
    v_data := v_data || jsonb_build_object(
      'thisTargetAllPlayerSkillStats',
      coalesce((
        select jsonb_object_agg(key, value)
        from jsonb_each(coalesce(v_data->'thisTargetAllPlayerSkillStats', '{}'::jsonb))
        where key = any(v_top_keys)
      ), '{}'::jsonb)
    );
  end if;

  -- 5. Prune combatInfos
  v_combat_infos := v_data->'combatInfos';
  v_target_id := v_data->>'targetId';

  -- 5a. Keep only the current target's targetInfo
  if v_target_id is not null then
    v_combat_infos := v_combat_infos || jsonb_build_object(
      'targetInfos',
      jsonb_build_object(
        v_target_id,
        v_combat_infos #> array['targetInfos', v_target_id]
      )
    );
  end if;

  -- 5b. Keep only actorInfos for top 12 players
  if v_top_keys is not null then
    v_combat_infos := v_combat_infos || jsonb_build_object(
      'actorInfos',
      coalesce((
        select jsonb_object_agg(key, value)
        from jsonb_each(coalesce(v_combat_infos->'actorInfos', '{}'::jsonb))
        where key = any(v_top_keys)
      ), '{}'::jsonb)
    );
  end if;

  v_data := jsonb_set(v_data, '{combatInfos}', v_combat_infos);

  -- 6. Return sanitized payload
  return jsonb_set(p_payload, '{data}', v_data);
end;
$$;

create or replace function public.process_aion2_dps_payload(
  p_payload jsonb,
  p_keep_limit integer default 50
)
returns jsonb
language plpgsql
security definer
as $$
declare
  v_record_id text;
  v_main_actor_name text;
  v_main_actor_server_id text;
  v_main_actor_class text;
  v_target_mob_code bigint;
  v_target_max_hp bigint;
  v_keep_limit integer;
  v_trimmed_count integer := 0;
  v_party_total_damage bigint := 0;
  v_boss_max_party_total_damage bigint;
  v_team_battle_duration double precision := 0;
  v_payload jsonb;
  v_ranked_player_count integer := 0;
begin
  v_payload := public.sanitize_aion2_dps_payload(coalesce(p_payload, '{}'::jsonb));

  v_record_id := nullif(trim(v_payload->>'record_id'), '');
  v_main_actor_name := coalesce(nullif(trim(v_payload->>'main_actor_name'), ''), '');
  v_main_actor_server_id := coalesce(trim(v_payload->>'main_actor_server_id'), '');
  v_main_actor_class := coalesce(trim(v_payload->>'main_actor_class'), '');
  v_target_mob_code := nullif(v_payload->>'target_mob_code', '')::bigint;
  v_target_max_hp := nullif(v_payload->>'target_max_hp', '')::bigint;
  v_keep_limit := greatest(1, least(coalesce(p_keep_limit, 50), 50));
  v_party_total_damage := coalesce((v_payload->>'party_total_damage')::bigint, 0);
  v_team_battle_duration := coalesce((v_payload->>'team_battle_duration')::double precision, 0);

  if v_record_id is null then
    raise exception 'record_id is required';
  end if;

  if v_main_actor_name = '' then
    raise exception 'main_actor_name is required';
  end if;

  if v_target_mob_code is null then
    raise exception 'target_mob_code is required';
  end if;

  if not (v_target_mob_code = any(array[
    2400032,
    2300219, 2300230, 2300200,
    2300243, 2300244, 2300245,
    2311402, 2311401, 2311403,
    2321402, 2321401, 2321403,
    2311302, 2311303, 2311301,
    2321302, 2321303, 2321301,
    2310508, 2310507, 2310509,
    2300154, 2300153, 2300155,
    2301503, 2301502, 2301501,
    2300002, 2300001, 2300000,
    2300017, 2300016, 2300015,
    2300032, 2300031, 2300030,
    2300259, 2300260, 2300261,
    2300299, 2300300, 2300317,
    2300334, 2300335, 2300336,
    2300353, 2300354, 2300355,
    2301006, 2301007, 2301014,
    2301209, 2301207, 2301208
  ])) then
      raise exception
        'mobcode (%) not allowed',
        v_target_mob_code;
  end if;

  if v_target_mob_code = 2400032 then
    if v_team_battle_duration < 60 then
      raise exception
        'team_battle_duration (%) must be at least 60 seconds for mob_code %',
        v_team_battle_duration,
        v_target_mob_code;
    end if;

  elsif coalesce(v_target_max_hp, 0) > 0 then
    if v_party_total_damage < (v_target_max_hp * 0.9) then
      raise exception
        'party_total_damage (%) must be at least 90%% of target_max_hp (%) for mob_code %',
        v_party_total_damage,
        v_target_max_hp,
        v_target_mob_code;
    end if;

  else
    v_boss_max_party_total_damage := public.get_aion2_dps_max_party_total_damage(v_target_mob_code);
    if coalesce(v_boss_max_party_total_damage, 0) > 0 then
      if v_party_total_damage < (v_boss_max_party_total_damage * 0.8) then
        raise exception
          'party_total_damage (%) must be at least 80%% of max party_total_damage (%) for mob_code %',
          v_party_total_damage,
          v_boss_max_party_total_damage,
          v_target_mob_code;
      end if;
    end if;
  end if;

  if v_target_mob_code <> 2400032 then
    insert into public.aion2_dps (
      record_id,
      created_at,
      battle_ended_at,
      target_mob_code,
      target_name,
      is_boss,
      target_max_hp,
      battle_start_time,
      battle_last_time,
      team_battle_duration,
      party_total_damage,
      team_dps,
      main_actor_name,
      main_actor_server_id,
      main_actor_class,
      main_actor_damage,
      main_actor_battle_duration,
      main_actor_dps,
      data
    )
    values (
      v_record_id,
      coalesce(nullif(v_payload->>'created_at', '')::timestamptz, now()),
      nullif(v_payload->>'battle_ended_at', '')::timestamptz,
      v_target_mob_code,
      nullif(v_payload->>'target_name', ''),
      coalesce((v_payload->>'is_boss')::boolean, false),
      v_target_max_hp,
      coalesce(v_payload->'battle_start_time', '{}'::jsonb),
      coalesce(v_payload->'battle_last_time', '{}'::jsonb),
      v_team_battle_duration,
      v_party_total_damage,
      coalesce((v_payload->>'team_dps')::double precision, 0),
      v_main_actor_name,
      v_main_actor_server_id,
      v_main_actor_class,
      coalesce((v_payload->>'main_actor_damage')::bigint, 0),
      coalesce((v_payload->>'main_actor_battle_duration')::double precision, 0),
      coalesce((v_payload->>'main_actor_dps')::double precision, 0),
      coalesce(v_payload->'data', '{}'::jsonb) - 'thisTargetAllPlayerSkillRecords'
    )
    on conflict (record_id) do nothing;

    delete from public.aion2_dps
    where record_id in (
      select record_id
      from (
        select
          record_id,
          row_number() over (
            partition by main_actor_name, main_actor_server_id
            order by battle_ended_at desc nulls last, created_at desc, record_id desc
          ) as rn
        from public.aion2_dps
        where main_actor_name = v_main_actor_name
          and main_actor_server_id = v_main_actor_server_id
      ) ranked
      where ranked.rn > v_keep_limit
    )
    and record_id not in (
      select record_id from public.aion2_dps_rank
    );

    get diagnostics v_trimmed_count = row_count;
  end if;

  insert into public.aion2_dps_rank (
    record_id,
    battle_ended_at,
    target_mob_code,
    target_name,
    is_boss,
    target_max_hp,
    team_battle_duration,
    party_total_damage,
    team_dps,
    main_actor_name,
    main_actor_server_id,
    main_actor_class,
    main_actor_damage,
    main_actor_battle_duration,
    main_actor_dps
  )
  with player_stats as (
    select
      stats.key as actor_id,
      stats.value as stat,
      actor.value as actor_info
    from jsonb_each(coalesce(v_payload #> '{data,thisTargetAllPlayerStats}', '{}'::jsonb)) stats
    left join jsonb_each(coalesce(v_payload #> '{data,combatInfos,actorInfos}', '{}'::jsonb)) actor
      on actor.key = stats.key
  ),
  player_rows as (
    select
      v_record_id as record_id,
      nullif(v_payload->>'battle_ended_at', '')::timestamptz as battle_ended_at,
      v_target_mob_code as target_mob_code,
      nullif(v_payload->>'target_name', '') as target_name,
      coalesce((v_payload->>'is_boss')::boolean, false) as is_boss,
      v_target_max_hp as target_max_hp,
      v_team_battle_duration as team_battle_duration,
      v_party_total_damage as party_total_damage,
      coalesce((v_payload->>'team_dps')::double precision, 0) as team_dps,
      coalesce(nullif(trim(actor_info->>'actorName'), ''), '') as main_actor_name,
      coalesce(nullif(trim(actor_info->>'actorServerId'), ''), '') as main_actor_server_id,
      coalesce(nullif(trim(actor_info->>'actorClass'), ''), '') as main_actor_class,
      coalesce(nullif(stat->>'total_damage', '')::bigint, 0) as main_actor_damage,
      greatest(
        0,
        coalesce(nullif(v_payload->'battle_last_time'->>actor_id, '')::double precision, 0)
          - coalesce(nullif(v_payload->'battle_start_time'->>actor_id, '')::double precision, 0)
      ) as main_actor_battle_duration
    from player_stats
  )
  select
    record_id,
    battle_ended_at,
    target_mob_code,
    target_name,
    is_boss,
    target_max_hp,
    team_battle_duration,
    party_total_damage,
    team_dps,
    main_actor_name,
    main_actor_server_id,
    main_actor_class,
    main_actor_damage,
    main_actor_battle_duration,
    main_actor_damage / nullif(main_actor_battle_duration, 0) as main_actor_dps
  from player_rows
  where main_actor_name <> ''
    and main_actor_damage > 0
    and main_actor_battle_duration > 0
  on conflict (main_actor_name, main_actor_server_id, target_mob_code)
  do update
  set
    record_id = excluded.record_id,
    battle_ended_at = excluded.battle_ended_at,
    target_name = excluded.target_name,
    is_boss = excluded.is_boss,
    target_max_hp = excluded.target_max_hp,
    team_battle_duration = excluded.team_battle_duration,
    party_total_damage = excluded.party_total_damage,
    team_dps = excluded.team_dps,
    main_actor_damage = excluded.main_actor_damage,
    main_actor_battle_duration = excluded.main_actor_battle_duration,
    main_actor_dps = excluded.main_actor_dps
  where
    excluded.main_actor_dps > public.aion2_dps_rank.main_actor_dps
    or (
      excluded.main_actor_dps = public.aion2_dps_rank.main_actor_dps
      and excluded.main_actor_damage > public.aion2_dps_rank.main_actor_damage
    )
    or (
      excluded.main_actor_dps = public.aion2_dps_rank.main_actor_dps
      and excluded.main_actor_damage = public.aion2_dps_rank.main_actor_damage
      and coalesce(excluded.battle_ended_at, '-infinity'::timestamptz)
        > coalesce(public.aion2_dps_rank.battle_ended_at, '-infinity'::timestamptz)
    );

  get diagnostics v_ranked_player_count = row_count;

  return jsonb_build_object(
    'success', true,
    'record_id', v_record_id,
    'trimmed_count', v_trimmed_count,
    'ranked_player_count', v_ranked_player_count
  );
end;
$$;

create or replace function public.insert_aion2_dps_and_update_rank(
  p_payload jsonb,
  p_keep_limit integer default 10
)
returns jsonb
language plpgsql
security definer
as $$
declare
  v_record_id text;
  v_payload jsonb;
  v_keep_limit integer;
begin
  v_payload := public.sanitize_aion2_dps_payload(coalesce(p_payload, '{}'::jsonb));
  v_record_id := nullif(trim(v_payload->>'record_id'), '');
  v_keep_limit := greatest(1, least(coalesce(p_keep_limit, 50), 50));

  if v_record_id is null then
    raise exception 'record_id is required';
  end if;

  insert into public.aion2_dps_ingest_queue (
    record_id,
    payload,
    keep_limit,
    status,
    attempts,
    error,
    processed_at
  )
  values (
    v_record_id,
    v_payload,
    v_keep_limit,
    'pending',
    0,
    null,
    null
  )
  on conflict (record_id) do update
  set
    payload = excluded.payload,
    keep_limit = excluded.keep_limit,
    status = 'pending',
    attempts = 0,
    error = null,
    processed_at = null;

  return jsonb_build_object(
    'success', true,
    'queued', true,
    'record_id', v_record_id
  );
end;
$$;

create or replace function public.process_aion2_dps_ingest_queue_batch(
  p_batch_size integer default 500,
  p_max_attempts integer default 3
)
returns table (
  picked_count integer,
  processed_count integer,
  failed_count integer
)
language plpgsql
security definer
as $$
declare
  v_job record;
  v_batch_size integer;
begin
  picked_count := 0;
  processed_count := 0;
  failed_count := 0;
  v_batch_size := greatest(1, least(coalesce(p_batch_size, 50), 500));

  for v_job in
    select id, payload, keep_limit, attempts
    from public.aion2_dps_ingest_queue
    where status in ('pending', 'failed')
      and attempts < greatest(1, coalesce(p_max_attempts, 3))
    order by created_at asc, id asc
    limit v_batch_size
    for update skip locked
  loop
    picked_count := picked_count + 1;

    update public.aion2_dps_ingest_queue
    set status = 'processing',
        attempts = attempts + 1,
        error = null
    where id = v_job.id;

    begin
      perform public.process_aion2_dps_payload(v_job.payload, v_job.keep_limit);

      delete from public.aion2_dps_ingest_queue
      where id = v_job.id;

      processed_count := processed_count + 1;
    exception when others then
      update public.aion2_dps_ingest_queue
      set status = 'failed',
          error = sqlerrm
      where id = v_job.id;

      failed_count := failed_count + 1;
    end;
  end loop;

  return next;
end;
$$;

create extension if not exists pg_cron;

select cron.unschedule(jobname)
from cron.job
where jobname = 'process-aion2-dps-ingest-queue';

select cron.schedule(
  'process-aion2-dps-ingest-queue',
  '* * * * *',
  $$
    select *
    from public.process_aion2_dps_ingest_queue_batch(500, 3);
  $$
);

select cron.unschedule(jobname)
from cron.job
where jobname in (
  'cleanup-aion2-dps-ingest-queue',
  'cleanup-aion2-dps-ingest-queue-failed'
);

select cron.schedule(
  'cleanup-aion2-dps-ingest-queue-failed',
  '0 0 * * *',
  $$
    delete from public.aion2_dps_ingest_queue
    where status = 'failed'
      and attempts >= 3;
  $$
);

-- Monitor recent runs:
-- select *
-- from cron.job_run_details
-- where jobid = (
--   select jobid
--   from cron.job
--   where jobname = 'process-aion2-dps-ingest-queue'
-- )
-- order by start_time desc
-- limit 20;
--
-- Monitor queue depth:
-- select status, count(*)
-- from public.aion2_dps_ingest_queue
-- group by status
-- order by status;
--
-- Retry jobs that failed before record_id was changed back to a non-unique rank lookup index:
-- update public.aion2_dps_ingest_queue
-- set status = 'pending',
--     attempts = 0,
--     error = null,
--     processed_at = null
-- where status = 'failed'
--   and error like '%idx_aion2_dps_rank_record_id%';
-- 
-- Stop the job:
-- select cron.unschedule('process-aion2-dps-ingest-queue');
-- select cron.unschedule('cleanup-aion2-dps-ingest-queue-failed');

-- Delete rank rows whose mob_code is not in the dungeons whitelist
-- delete from public.aion2_dps_rank
-- where target_mob_code not in (
--   2400032,
--   2300219, 2300230, 2300200,
--   2300243, 2300244, 2300245,
--   2311402, 2311401, 2311403,
--   2321402, 2321401, 2321403,
--   2311302, 2311303, 2311301,
--   2321302, 2321303, 2321301,
--   2310508, 2310507, 2310509,
--   2300154, 2300153, 2300155,
--   2301503, 2301502, 2301501,
--   2300002, 2300001, 2300000,
--   2300017, 2300016, 2300015,
--   2300032, 2300031, 2300030,
--   2300259, 2300260, 2300261,
--   2300299, 2300300, 2300317,
--   2300334, 2300335, 2300336,
--   2300353, 2300354, 2300355,
--   2301006, 2301007, 2301014,
--   2301209, 2301207, 2301208
-- );
-- delete from public.aion2_dps
-- where target_mob_code not in (
--   2400032,
--   2300219, 2300230, 2300200,
--   2300243, 2300244, 2300245,
--   2311402, 2311401, 2311403,
--   2321402, 2321401, 2321403,
--   2311302, 2311303, 2311301,
--   2321302, 2321303, 2321301,
--   2310508, 2310507, 2310509,
--   2300154, 2300153, 2300155,
--   2301503, 2301502, 2301501,
--   2300002, 2300001, 2300000,
--   2300017, 2300016, 2300015,
--   2300032, 2300031, 2300030,
--   2300259, 2300260, 2300261,
--   2300299, 2300300, 2300317,
--   2300334, 2300335, 2300336,
--   2300353, 2300354, 2300355,
--   2301006, 2301007, 2301014,
--   2301209, 2301207, 2301208
-- );
